name: Debug Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build Project
        run: go build -trimpath -ldflags "-w -s -H windowsgui"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cafetime
          path: cafetime.exe